const VendorMapper = (vendor)=>({
    _id:vendor._id,
    username: vendor.username,
    email: vendor.email,
    role: vendor.role,
    displayName:vendor.displayName,
    profilePic:vendor.profilePic?.url || null,
    isActive:vendor.isActive,
    kycStatus:vendor.kycStatus,
    isKycApproved:vendor.isKycApproved,
    rejectedReason:vendor.rejectedReason,
    images:vendor.dairyImages,
    videos:vendor.dairyVideos,
    contactnumbers:vendor.contactnumbers,
    deliveryTimings:vendor.deliveryTimings,
    description:vendor.description,
    city:vendor.city,
    pincode:vendor.pincode,
})
module.exports = VendorMapper